name: EOL Dependencies Check
on:
  schedule:
    - cron: '0 11 * * 1'  # Weekly on Mondays at 11:00 UTC
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  eol_dependency_check:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-eol-analysis.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    with:
      java_version: '25'
      java_distribution: 'temurin'