name: License Compliance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check_licences:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-licences-analysis.yml@52c11f63f46f741e4f56c5dace97b44982a4372b
    name: Analyse Licences
    with:
      java_version: '25'
      java_distribution: 'temurin'
      create-review: true
    secrets:
      token: ${{ secrets.GITLAB_API_TOKEN }}
