
name: Maven Build & Sonar Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  maven_build:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-maven-run.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    name: Maven Build
    with:
      java_version: '25'
      java_distribution: 'temurin'
      maven_args: 'clean package --file pom.xml'
      test-report: true
      summaries-test-report: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sonar_analysis:
    needs: maven_build
    uses: eclipse-ecsp/.github/.github/workflows/workflow-sonar-analysis.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    with:
      java_version: '25'
      java_distribution: 'temurin'
    secrets:
      token: ${{ secrets.SONAR_TOKEN }}
  dependencies_update:
    needs: sonar_analysis
    uses: eclipse-ecsp/.github/.github/workflows/workflow-dependencies-update.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    secrets:
      ECSP_BOT_PAT: ${{ secrets.ECSP_BOT_PAT }}
    with:
      java_version: '25'
      java_distribution: 'temurin'
    permissions:
      pull-requests: write
      contents: read
  deploy-snapshot:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-publish-artifacts.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    needs: sonar_analysis
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      CENTRAL_SONATYPE_TOKEN_USERNAME: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
      CENTRAL_SONATYPE_TOKEN_PASSWORD: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
    with:
      java_version: '25'
      java_distribution: 'temurin'
